# Backstage Catalog Entity
# This file registers the S3 bucket as a component in Backstage
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3-${{ values.bucketName }}
  title: S3 Bucket - ${{ values.bucketName }}
  description: ${{ values.description or "S3 bucket managed by Crossplane" }}
  annotations:
    # Kubernetes plugin - view resources
    backstage.io/kubernetes-id: s3-${{ values.bucketName }}
    backstage.io/kubernetes-namespace: default
    
    # ArgoCD plugin - view sync status
    argocd/app-name: s3-${{ values.bucketName }}
    
    # GitHub integration
    github.com/project-slug: manifest-crossplane-poc/infra-s3-${{ values.bucketName }}
    
    # Techdocs (optional)
    backstage.io/techdocs-ref: dir:.
  
  labels:
    environment: ${{ values.environment }}
    resource-type: s3-bucket
    provider: aws
  
  tags:
    - aws
    - s3
    - storage
    - crossplane
    - ${{ values.environment }}
  
  links:
    - url: https://console.aws.amazon.com/s3/buckets/${{ values.bucketName }}
      title: AWS Console
      icon: cloud
    - url: https://argocd.example.com/applications/s3-${{ values.bucketName }}
      title: ArgoCD Application
      icon: dashboard

spec:
  type: resource
  lifecycle: production
  owner: ${{ values.owner }}
  system: infrastructure
  
  # Dependencies (optional)
  # dependsOn:
  #   - resource:aws-vpc
  
  # APIs provided (optional)
  # providesApis:
  #   - s3-api
