apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rds-${{ values.databaseName }}
  title: RDS Database - ${{ values.databaseName }}
  description: ${{ values.description or "RDS database managed by Crossplane" }}
  annotations:
    backstage.io/kubernetes-id: rds-${{ values.databaseName }}
    backstage.io/kubernetes-namespace: default
    argocd/app-name: rds-${{ values.databaseName }}
    github.com/project-slug: manifest-crossplane-poc/infra-rds-${{ values.databaseName }}
  labels:
    environment: ${{ values.environment }}
    resource-type: rds-database
    provider: aws
  tags:
    - aws
    - rds
    - database
    - crossplane
    - ${{ values.environment }}
spec:
  type: resource
  lifecycle: production
  owner: ${{ values.owner }}
  system: infrastructure
