apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-staging
  namespace: argocd
  labels:
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/manifest-crossplane-poc/gitops.git
    targetRevision: main
    path: environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
