apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/manifest-crossplane-poc/gitops.git
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    # Manual sync for production - requires explicit approval
    syncOptions:
      - CreateNamespace=true
